FROM python:3.8-slim

COPY client.py /app/client.py
COPY client_requirements.txt .
COPY models.py /app/models.py

RUN pip install -r client_requirements.txt

WORKDIR /app

CMD ["python", "client.py"]
