FROM grafana/grafana:latest
COPY grafana.ini /etc/grafana/grafana.ini
COPY provisioning/datasources /etc/grafana/provisioning/datasources
COPY provisioning/dashboards /etc/grafana/provisioning/dashboards
CMD ["--config=/etc/grafana/grafana.ini"]
