{
 "title": "Cadvisor exporter Dashbo",
 "description": "Simple exporter for cadvisor only",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$host\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Model Accuracy",
   "type": "timeseries",
   "description": "Averaged federated accuracy across clients",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "model_accuracy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model Loss",
   "type": "timeseries",
   "description": "Averaged Federated Loss across clients",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "model_loss", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$host\",name=~\"$container\",name=~\".+\", name !~ \"(prometheus|cadvisor|grafana)\"}[10s])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$host\",name=~\"$container\",name=~\".+\", name !~ \"(prometheus|cadvisor|grafana)\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{instance=~\"$host\",name=~\"$container\",name=~\".+\", name !~ \"(prometheus|cadvisor|grafana)\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_receive_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\", name!~\"(prometheus|cadvisor|grafana)\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_transmit_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\", name!~\"(prometheus|cadvisor|grafana)\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\", name!~\"prometheus|cadvisor|grafana\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transmit Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\", name!~\"prometheus|cadvisor|grafana\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_network_receive_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\", name!~\"prometheus|cadvisor|grafana\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transmit Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\", name!~\"prometheus|cadvisor|grafana\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total{instance=~\"$host\", name=~\".+\", name!~\"prometheus|grafana|cadvisor\", name=\"server\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_network_receive_bytes_total{instance=~\"$host\", name=~\".+\", name!~\"prometheus|grafana|cadvisor|server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total{instance=~\"$host\", name=~\".+\", name!~\"prometheus|grafana|cadvisor\", name!=\"server\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_network_receive_bytes_total{instance=~\"$host\", name=~\".+\", name!~\"prometheus|grafana|cadvisor\", name=\"server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recived",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(container_network_receive_packets_total{instance=~\"$host\", name=~\".+\", name!~\"prometheus|grafana|cadvisor\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_network_receive_packets_dropped_total{instance=~\"$host\", name=~\".+\", name!~\"prometheus|grafana|cadvisor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum(container_network_transmit_packets_total{instance=~\"$host\", name=~\".+\", name!~\"prometheus|grafana|cadvisor\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_network_transmit_packets_dropped_total{instance=~\"$host\", name=~\".+\", name!~\"prometheus|grafana|cadvisor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{instance=~\"$host\",name=~\"$container\",name=~\".+\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}