version: '3.8'

services:
  server:
    image: 'fl-server:latest'
    container_name: fl_server
    environment:
      - SERVER_IP=0.0.0.0:9999
    networks:
      - default

  client-0:
    image: 'fl-client:latest'
    environment:
      - SERVER_IP=fl_server:9999
    networks:
      - default

  client-1:
    image: 'fl-client:latest'
    environment:
      - SERVER_IP=fl_server:9999
    networks:
      - default
