services:
  server:
    image: ${SERVER_IMAGE}
    container_name: fl_server
    environment:
      - SERVER_IP=${SERVER_IP}
      - MODEL=${MODEL}
      - DATASET=${DATASET}
    networks:
      - default

  client-0:
    image: 'fl-client:latest'
    environment:
      - SERVER_IP=fl_server:9999
      - MODEL=${MODEL}
      - DATASET=${DATASET}
      - CLIENT_ID=0
    networks:
      - default

  client-1:
    image: 'fl-client:latest'
    environment:
      - SERVER_IP=fl_server:9999
      - MODEL=${MODEL}
      - DATASET=${DATASET}
      - CLIENT_ID=1
    networks:
      - default
